"ProjectsA:Python:Pyrex:Tests:Errors2:se_multass.pyx":2:33: Unpacking sequence of wrong size (expected 2, got 3)
